name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8000:8000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose build

    - name: Run Docker Compose
      run: |
        docker-compose up -d

    - name: Run tests
      env:
        PYTEST_ARGS: "-s -v --html=test_results/report.html --self-contained-html --capture=sys"
      run: |
        docker-compose exec tests pytest ${PYTEST_ARGS}

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: tests/test_results/report.html

    - name: Tear down Docker Compose
      if: always()
      run: |
        docker-compose down
